OpenBangla/OpenBangla-Keyboard

src/frontend/TopBar.cpp, src/frontend/TopBar.ui
Added:
X11 Window Manager Bypass TaskBar -> Qt::X11BypassWindowManagerHint
No Focus Window -> Qt::WindowDoesNotAcceptFocus
Disable Shadowed Window -> Qt::NoDropShadowWindowHint
=> Better Integration with X11

tools/install.sh
It will be easier to update the link. Sorry, It did not come to mind while I was writing it
=> added variable to easily edit binnary link

tools/install.sh
in other words, install.sh makeup! :grinning: 
ref #43 | resolves #50
=> remove python dependency from install script

tools/install.sh
Let's give `install.sh` a makeup! :tada: 
**edit:**
This PR also Closes #53  by the great work by @bdeshi
=> 💄 install.sh 💄

CMakeLists.txt, cmake/cmake_uninstall.cmake.in
=> cmake generator for `make uninstall`

tools/install.sh
This looks more convenient. Should we add this prompt?
=> Added prompt to visit the website

src/frontend/TopBar.ui
Revert back the changes until we find a way to remove the padding in the layout.
=> Revert back TopBar.ui changes.

tools/install.sh
This PR adds ubuntu 18.10 to the supported version list.
=> PR for Fix of #90

src/frontend/SettingsDialog.ui
Added grid layout after the change.
=> Added Grid Layout

src/shared/FileSystem.cpp, src/shared/FileSystem.h
Follow XDG Directory Specification for storing user specific data.
Closes #16
=> Follow XDG Directory Specification

.gitignore, src/frontend/SettingsDialog.cpp, src/frontend/SettingsDialog.h, src/frontend/SettingsDialog.ui, src/frontend/TopBar.cpp, src/frontend/TopBar.h
This is how it looks on my machine with `AdaptaDark` Theme.
Closes #110 
Closes #112
=> Layout for new Settings UI 

src/engine/ibus/main.cpp, src/frontend/SettingsDialog.cpp, src/frontend/SettingsDialog.h, src/frontend/SettingsDialog.ui, src/shared/Settings.cpp, src/shared/Settings.h
:tada: :tada: :tada:
I have also updated the settings dialog to reflect the change in the feature.
Closes #121
=> Implement the Include English word feature!

README.adoc
https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported
=> Change pacman -Sy in README

src/engine/ibus/main.cpp, src/frontend/SettingsDialog.cpp, src/frontend/SettingsDialog.ui, src/shared/Settings.cpp, src/shared/Settings.h
* Added the option for showing preview window in the Fixed method settings list.
* Updated the layout of the dialog.
=> Update Settings Dialog

src/frontend/SettingsDialog.cpp, src/frontend/SettingsDialog.ui
=> Settings dialog redesign take 2!

CHANGELOG.md
[Rendered](https://github.com/OpenBangla/OpenBangla-Keyboard/blob/changelog/CHANGELOG.md)
=> Update the changelog for 2.0.0

README.adoc, README.bn.adoc
=> Add build deps installation instructions for Opensuse & derivatives

README.adoc, README.bn.adoc
=> Add build deps installation instructions for solus

cmake/CMakeCargo.cmake
Tested only with Void Linux (xbps-src)
=> Workaround to enable cross-compilation

CODE_OF_CONDUCT.md
added the Code of Conduct and fixed the issue no. #257
=> fixed Missing the Code of Conduct in the main/master branch #257

src/engine/fcitx/openbangla.cpp, src/engine/ibus/main.cpp, src/frontend/SettingsDialog.cpp, src/frontend/SettingsDialog.ui, src/frontend/TopBar.cpp, src/frontend/TopBar.h, src/shared/Settings.cpp, src/shared/Settings.h
:tada: 
:heavy_check_mark:  TODOS: 
Closes #217
=> ANSI encoding support! :rocket: 

.github/workflows/deploy.yml, tools/build.sh
=> OpenSuse Tumbleweed Package building

tools/install.sh
In wget2 --show-progress not available. For now, I got no way to show the progress bar.
=> Working install.sh for Fedora 41

CONTRIBUTING.md
This pull request introduces the `CONTRIBUTING.md` file to the repository.
This file aims to provide clear guidelines for individuals interested in contributing to the OpenBangla Keyboard project. It outlines the process for reporting bugs, suggesting new features, contributing code, and improving documentation.
Key aspects covered in this document include:
- Reporting bugs and suggesting enhancements.
- The workflow for contributing code (forking, branching, pull requests).
- Guidelines for commit messages.
- Pull request best practices.
- How to contribute to documentation.
- Where to ask questions (GitHub Discussions).
Closes: #401
=> Docs: Add CONTRIBUTING.md for contribution guidelines

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Reference: https://github.com/OpenBangla/OpenBangla-Keyboard/discussions/396#discussioncomment-13002122
=> feat: Add issue templates for bug reports and feature requests

CONTRIBUTING.md
Removes verbose git command examples and integrates documentation contribution steps. Adds emphasis on Conventional Commits and Semantic PR to align with modern best practices for version control and PR management.
=> docs: simplify and improve CONTRIBUTING.md
