OpenBangla/OpenBangla-Keyboard

- README.md
Added instructions for installing from AUR on Arch.
I'm maintaining a PKGBUILD at:
https://aur.archlinux.org/packages/openbangla-keyboard/
> update install instructions with aur

- .vscode/c_cpp_properties.json
- src/engine/ibus/ibus_engine.cpp
- src/engine/libengine/Layout.cpp
- src/engine/libengine/Layout.h
- src/engine/libengine/MethodFixedLayoutModern.cpp
- src/engine/libengine/MethodFixedLayoutModern.h
- src/engine/libengine/MethodPhonetic.cpp
- src/engine/libengine/MethodPhonetic.h
- src/engine/libengine/PhoneticSuggestion.cpp
- src/engine/libengine/PhoneticSuggestion.h
- src/engine/libengine/cachemanager.cpp
- src/engine/libengine/cachemanager.h
This also fixes a bug which I faced when saving a selection.
> Be less restrictive when saving users selection.

- src/engine/libengine/Database.cpp
- src/engine/libengine/Database.h
- src/engine/libengine/MethodPhonetic.cpp
- src/engine/libengine/MethodPhonetic.h
- src/engine/libengine/PhoneticSuggestion.cpp
- src/engine/libengine/PhoneticSuggestion.h
:tada: :confetti_ball:
I have always to do this kind of optimization and refactoring for a long time. I believe this would improve the performance of phonetic suggestion making. Now if any autocorrect suggestion is available, it would be shown as the first item of the suggestion list.
> Suggestion making code overhaul!

- README.adoc
"OpenBangla Keyboard is the default Bangla writing software for [MagpieOS](http://www.magpieos.net), the first Bangladeshi Linux distribution."
cc @Rizwan-Hasan
> Add info about MagpieOS

- src/engine/ibus/ibus_engine.cpp
- src/engine/libengine/Layout.h
- src/engine/libengine/MethodPhonetic.cpp
Commit the originally typed text or auxiliary text on <kbd>Ctrl + B</kbd> keypress.
> Commit the auxiliary text on Ctrl + B keypress

- src/engine/ibus/ibus_engine.cpp
- src/engine/libengine/Layout.cpp
- src/engine/libengine/Layout.h
- src/frontend/SettingsDialog.cpp
- src/frontend/SettingsDialog.h
- src/frontend/SettingsDialog.ui
- src/shared/Settings.cpp
- src/shared/Settings.h
The default key has been changed into `Ctrl + T`.
Closes #93
> Make the commit raw text key customizable.

- data/openbangla-keyboard.desktop.in
- data/openbangla.xml.in
- src/engine/ibus/CMakeLists.txt
- src/engine/ibus/ibus_engine.cpp
- src/frontend/CMakeLists.txt
> Change the binary file names

- src/frontend/LayoutViewer.cpp
- src/frontend/LayoutViewer.h
- src/frontend/LayoutViewer.ui
* Layout viewer is now resizable.
* Window contents dynamically resize along with the dialog.
* Removed the unimplemented Zooming buttons.
* View buttons dynamically enable itself with respect to the selected dialog.
* About Layout is now simply a button with an icon.
* Layout Viewer now handles layout without an image gracefully.
Closes #115
> Redesign the Layout viewer dialog

- src/engine/ibus/keycode.h
- src/engine/ibus/main.cpp
Now key handling code is much simplified in `riti`.
I think this should make implementing #152 much easier.
> Handle modifiers and special keys in the engine

- src/frontend/AutoCorrectDialog.cpp
- src/frontend/AutoCorrectDialog.ui
* Uses QGroupBox instead of QFrame which can be named.
* Previewing labels uses a different style.
* The dialog is now resizable.
> Polish the Auto Correct dialog

- src/frontend/TopBar.cpp
- src/frontend/TopBar.ui
* Removed `Qt::X11BypassWindowManagerHint` to prevent nasty bugs like #153 where the window manager loses the track of the TopBar.
* Removed `Qt::WindowDoesNotAcceptFocus` to get tooltips on the TopBar buttons.
* Removed `Qt::NoDropShadowWindowHint` as this doesn't prevent drop shadow of Topbar anyway and I don't think having shadow around the TopBar when it has focus is a bad choice.
* Tooltip updates.
cc @ahmubashshir
> Don't bypass the window manager

- .github/workflows/deploy.yml
- src/frontend/LayoutViewer.cpp
- tools/README.md
- tools/build.sh
* Adds a leeway `pkg+` to build packages only and upload them as GHA artifacts.
* Backwards compatibility with zstd >= 1.1.2 to fix the build failure in Debian 9. (Previously we depended on zstd >= 1.3.0)
* Use **rustup** to install the latest Rust stable version available in Ubuntu, Debian and Fedora distributions.
[Here's the successful build with `pkg+` and all of these changes.](https://github.com/OpenBangla/OpenBangla-Keyboard/actions/runs/273794360)
> Update DEPLOY workflow

- CMakeLists.txt
- data/openbangla-keyboard.desktop.in
- data/openbangla.xml.in
- src/engine/ibus/CMakeLists.txt
- src/frontend/CMakeLists.txt
This resolves the issue raised in #183 
Now the executable files are installed in:
```
/usr/bin/ibus-openbangla
/usr/bin/openbangla-gui
```
@natrys can you check it, please?
> Maintain Filesystem Hierarchy Standard while installing binary executable files

- CMakeLists.txt
- src/frontend/CMakeLists.txt
- src/frontend/SettingsDialog.cpp
- src/frontend/SettingsDialog.ui
- src/frontend/TopBar.cpp
- src/frontend/TopBar.h
This PR introduces a CMake variable `NO_UPDATE_CHECK` to control the inclusion and linking of the `QSimpleUpdater` project code which is licensed under the [`DBAD`](https://dbad-license.org/) license and does not comply with the Debian Free Software Guidelines (DFSG).
This variable can be enabled by passing CMake the `-D NO_UPDATE_CHECK=1` flag to not include the above update checking code.
cc @gunnarhj
> Controlling the inclusion of 3rdParty code(QSimpleUpdater)

- .github/workflows/deploy.yml
- README.adoc
- README.bn.adoc
- tools/build.sh
- tools/install.sh
Bintray will be not available by May 1st. Unfortunately, we don't have any other way than suggesting to use `install.sh` to the users to download & install OBK easily.
* Have to update the Releases page with new packages and rename some packages to match with the `install.sh` package name convention.
cc @Adyel @bdeshi @ahmubashshir review, please.
Can we add debian disrto detection in `install.sh` as we're now building packages for debian also?
> `install.sh` again :pensive:

- .github/workflows/ci.yml
- CMakeLists.txt
- data/openbangla-keyboard.desktop.in
- src/engine/CMakeLists.txt
- src/engine/fcitx/openbangla.h
- src/frontend/CMakeLists.txt
Now it's possible to override `BIN_DIR`, `DATADIR` & `LIBEXECDIR` and building IM backends on the basis of build-time variables, Passing CMake the `-DENABLE_IBUS=ON` flag will build the `ibus` backend(Default) while passing the `-DENABLE_FCITX` flag will build the `fcitx` backend. I think this will help to split the package as we had discussed on #219 
cc @gunnarhj  @ahmubashshir
> Build system configuration

- src/frontend/TopBar.cpp
- src/frontend/TopBar.h
- src/frontend/main.cpp
- src/shared/Settings.cpp
- src/shared/Settings.h
This implements saving the visibility of the TopBar while closing it and views the TopBar in the same way(hidden or shown) in the next run. If the TopBar is hidden while starting, it will notify the user of running in the system tray for the first three times.
> View the TopBar according to the last state of it 

- src/engine/fcitx/openbangla.cpp
- src/engine/ibus/main.cpp
- src/frontend/Layout.cpp
- src/frontend/SettingsDialog.cpp
- src/frontend/SettingsDialog.ui
- src/shared/Settings.cpp
- src/shared/Settings.h
This update of the `riti` submodule brings:
* **[`okkhor`](https://github.com/gulshan/okkhor) as the new phonetic transliteration crate**: `okkhor` is a faster implementation of Avro Phonetic by @gulshan, which is [quite faster](https://gist.github.com/mominul/3efb234767f889d88a3026fe2a01384a) than the previous implementation `rupantor`. :rocket: 
* **Fixed Method Old Kar Ordering**: This feature implemented by @NabilSnigdho enables writing in the old kar ordering aka placing kars before consonants with the fixed method layouts. :tada: 
Other change:
* Inclusion of typed English text in the suggestion list setting of both Phonetic & Fixed method is now merged into one option under the general group.
* Adds an entry for controlling the **Fixed Method Old Kar Ordering**.
> Update the `riti` submodule

- src/engine/fcitx/openbangla.cpp
- src/engine/ibus/main.cpp
This fixes the key rejection bug when typing with Old style kar enabled and suggestions are turned off(lone suggestion mode enabled).
fixes #235
> Fix the key rejection bug

- src/engine/fcitx/openbangla.cpp
Workaround for fixing the bug: When selecting a candidate with `fcitx::CommonCandidateList::setGlobalCursorIndex()` and the regarding index is not on the first page(assume the intended candidate is on the second page) of the candidate list, the candidate remains unselected and the first page is shown.
> Fix Fcitx CandidateList paging issue

- .github/workflows/deploy.yml
- tools/install.sh
Update `install.sh` and gh-actions to build packages for newer distro releases.
New distros:
* ubuntu 22.04
* debian 11
* fedora 35
* fedora 36
EOL distros have been removed from the build list.
Closes #291 
cc @bdeshi @ahmubashshir
> Update install.sh and gh-actions

- src/engine/fcitx/openbangla.cpp
- src/engine/ibus/main.cpp
- src/frontend/SettingsDialog.cpp
- src/frontend/SettingsDialog.ui
- src/shared/Settings.cpp
- src/shared/Settings.h
With `Kalpurush` Unicode font:
With `Kalpurush ANSI` ANSI font:
Option in Settngs to control the feature:
Closes #284
> Smart Quoting feature

- src/engine/fcitx/openbangla.cpp
- src/engine/ibus/main.cpp
This PR:
* Implements whole word deletion feature aka <kbd>Ctrl</kbd> + <kbd>Backspace</kbd> combination. Closes #299 
* Fixes focus out behavior of preedit text in IBus engine. Thanks @mike-fabian for proposing the fix! Fixes #298
> Whole word deletion feature and preedit text focus out behavior bug fix

- CMakeLists.txt
* Configure CPack based on which backend we are building for
* Make building for at least a backend a necessary choice and avoid defaults
> CMake and CPack modifications

- src/engine/ibus/main.cpp
Resolves: https://github.com/OpenBangla/OpenBangla-Keyboard/issues/308
This is called when the cursor position is changed with the mouse.
It causes the preedit to be committed and prevents the preedit from
reappearing at the new position.
> Add a callback engine_reset_cb

- README.adoc
Apt on Ubuntu now returns error saying the qt5-default package has no installation candidate. Instead we can use qtbase5-dev package as it is officially available on the repository. Also it is recommended from KDE community to not use the qt5-default package as a build dependency and to use qtbase5-dev instead. I also added the qt5-qmake package as the project uses qmake to generate makefiles.
> Replace qt5-default with qtbase5-dev

- README.bn.adoc
This replaces `qt5-default` with `qtbase5-dev` and `qtbase5-dev-tools`.
> README.bn.adoc: edit compile deps for Ubuntu

- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- CMakeLists.txt
- src/frontend/main.cpp
- tools/build.sh
This PR implements package building for ibus and fcitx5 backends for Debian, Ubuntu, and Fedora distributions. However, for Archlinux, it is not implemented.
* `qEnvironmentVariable` is available from Qt 5.10, so use the alternative `qgetenv` function.
* Print the Qt5 framework version while CMake runs.
* Use the `ubuntu-latest` image, which now contains the fcitx 5.0.5 development library.
> Build packages for ibus and fcitx in Github Actions

- src/frontend/LayoutConverter.cpp
- src/frontend/LayoutConverter.h
- src/frontend/TopBar.cpp
As suggested in #345, this adds option to import OBK *.json layout file.
~~Support for version 1 layout format is not added.~~
> feat: add option to import OBK *.json layout file

- CHANGELOG.md
- src/engine/fcitx/openbangla.cpp
- src/engine/ibus/main.cpp
In phonetic method, preserve user's candidate selection if the keypress was a punctuation mark.
Implements #361 
cc @larina3315
> Preserve user's selection if the keypress was a punctuation mark

- CMakeLists.txt
- src/engine/fcitx/openbangla.cpp
- src/shared/FileSystem.cpp
This would be required for flatpak / nixos to work without patch.
Also bsd system uses /usr/local instead of /usr by default.
> Use the CMAKE_INSTALL_PREFIX instead of hardcoded /usr/share for loading data

- README.adoc
The `cargo` package no longer exists and is part of the `rust` package nowadays.
> README: Update Solus packages
